export const SET_LANG = "SET_LANG";

// GET
export const GET_MAIN = "GET_MAIN";
export const GET_MAIN_FAILED = "GET_MAIN_FAILED";
export const GET_MAIN_SUCCESS = "GET_MAIN_SUCCESS";

export const GET_LOCAL_NEWS = "GET_LOCAL_NEWS";
export const GET_LOCAL_NEWS_FAILED = "GET_LOCAL_NEWS_FAILED";
export const GET_LOCAL_NEWS_SUCCESS = "GET_LOCAL_NEWS_SUCCESS";

export const GET_VIDEO_NEWS = "GET_VIDEO_NEWS";
export const GET_VIDEO_NEWS_FAILED = "GET_VIDEO_NEWS_FAILED";
export const GET_VIDEO_NEWS_SUCCESS = "GET_VIDEO_NEWS_SUCCESS";

export const GET_FEDERATIONS = "GET_FEDERATIONS";
export const GET_FEDERATIONS_FAILED = "GET_FEDERATIONS_FAILED";
export const GET_FEDERATIONS_SUCCESS = "GET_FEDERATIONS_SUCCESS";

export const GET_FEDERATION_SPORTS = "GET_FEDERATION_SPORTS";
export const GET_FEDERATION_SPORTS_FAILED = "GET_FEDERATION_SPORTS_FAILED";
export const GET_FEDERATION_SPORTS_SUCCESS = "GET_FEDERATION_SPORTS_SUCCESS";

// PATCH
export const PATCH_SPORT_NEWS_VIEWS = "PATCH_SPORT_NEWS_VIEWS";
export const PATCH_SPORT_NEWS_VIEWS_SUCCESS = "PATCH_SPORT_NEWS_VIEWS_SUCCESS";
export const PATCH_SPORT_NEWS_VIEWS_FAILED = "PATCH_SPORT_NEWS_VIEWS_FAILED";
